<a href="https://colab.research.google.com/github/kt-aakash/Scaler-DSML-Dec2022/blob/main/Varinance_Inflation_Factor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd

#importing statsmodels
import statsmodels.api as sm

#importing sklearn modules
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
#downloading the dataset
!gdown 1UpLnYA48Vy_lGUMMLG-uQE1gf_Je12Lh

Downloading...
From: https://drive.google.com/uc?id=1UpLnYA48Vy_lGUMMLG-uQE1gf_Je12Lh
To: /content/cars24-car-price-clean.csv
100% 7.10M/7.10M [00:00<00:00, 90.3MB/s]

In [6]:
#creating the dataframe
df = pd.read_csv('cars24-car-price-clean.csv')
df.head()

,selling_price,year,km_driven,mileage,engine,max_power,age,make,model,Individual,Trustmark Dealer,Diesel,Electric,LPG,Petrol,Manual,5,>5
0,-1.111046,-0.801317,1.195828,0.045745,-1.310754,-1.157780,0.801317,-0.433854,-1.125683,1.248892,-0.098382,-0.985275,-0.020095,-0.056917,1.024622,0.495818,0.444503,-0.424728
1,-0.223944,0.450030,-0.737872,-0.140402,-0.537456,-0.360203,-0.450030,-0.327501,-0.333227,1.248892,-0.098382,-0.985275,-0.020095,-0.056917,1.024622,0.495818,0.444503,-0.424728
2,-0.915058,-1.426990,0.035608,-0.582501,-0.537456,-0.404885,1.426990,-0.327501,-0.789807,1.248892,-0.098382,-0.985275,-0.020095,-0.056917,1.024622,0.495818,0.444503,-0.424728
3,-0.892365,-0.801317,-0.409143,0.329620,-0.921213,-0.693085,0.801317,-0.433854,-0.905265,1.248892,-0.098382,-0.985275,-0.020095,-0.056917,1.024622,0.495818,0.444503,-0.424728
4,-0.182683,0.137194,-0.544502,0.760085,0.042999,0.010435,-0.137194,-0.246579,-0.013096,-0.800710,-0.098382,1.014945,-0.020095,-0.056917,-0.975970,0.495818,0.444503,-0.424728

In [9]:
Y = df[['selling_price']]
X = df.drop('selling_price', axis=1)
#print(X)
#print(Y)

In [12]:
#splitting the dataset into training and testing data
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2, random_state=1)

In [14]:
#Feature Scaling using StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_train_scaled

array([[ 1.08056089, -0.74063651,  0.2289024 , ...,  0.49672619,
         0.4466381 , -0.42605178],
       [ 1.08056089, -0.74063651,  0.31846093, ..., -2.01318155,
         0.4466381 , -0.42605178],
       [-0.1701416 ,  0.05260843,  0.2289024 , ...,  0.49672619,
         0.4466381 , -0.42605178],
       ...,
       [ 0.45520964, -0.53288188,  1.30130835, ...,  0.49672619,
         0.4466381 , -0.42605178],
       [-0.79549285, -0.07959906, -1.71153236, ...,  0.49672619,
        -2.23894918,  2.34713255],
       [-1.10816847,  0.22258949,  0.37127749, ...,  0.49672619,
         0.4466381 , -0.42605178]])

In [16]:
X_train_scaled_df = pd.DataFrame(X_train_scaled, columns = X_train.columns)
X_train_scaled_df.head()

,year,km_driven,mileage,engine,max_power,age,make,model,Individual,Trustmark Dealer,Diesel,Electric,LPG,Petrol,Manual,5,>5
0,1.080561,-0.740637,0.228902,0.202493,0.622383,-1.080561,-0.328974,1.373254,1.248462,-0.098382,1.012694,-0.022468,-0.056805,-0.974714,0.496726,0.446638,-0.426052
1,1.080561,-0.740637,0.318461,-0.535794,-0.361629,-1.080561,-0.435239,-0.195688,-0.800986,-0.098382,-0.987465,-0.022468,-0.056805,1.025942,-2.013182,0.446638,-0.426052
2,-0.170142,0.052608,0.228902,0.233176,0.119296,0.170142,-0.242346,-0.431817,-0.800986,-0.098382,1.012694,-0.022468,-0.056805,-0.974714,0.496726,0.446638,-0.426052
3,-0.482817,0.241476,0.734104,0.041413,-0.183443,0.482817,-0.248121,-0.400333,-0.800986,-0.098382,1.012694,-0.022468,-0.056805,-0.974714,0.496726,0.446638,-0.426052
4,0.455210,-0.022939,1.308197,-0.437995,-0.534496,-0.455210,-0.435239,-0.353107,-0.800986,-0.098382,1.012694,-0.022468,-0.056805,-0.974714,0.496726,0.446638,-0.426052

In [41]:
## Preparing dataset to use statsmodels
X_sm = sm.add_constant(X_train_scaled_df)
Y_train_array = np.array(Y_train)
model = sm.OLS(Y_train_array, X_sm)
results = model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.941
Model:                            OLS   Adj. R-squared:                  0.941
Method:                 Least Squares   F-statistic:                 1.578e+04
Date:                Tue, 15 Aug 2023   Prob (F-statistic):               0.00
Time:                        06:40:48   Log-Likelihood:                -25.857
No. Observations:               15856   AIC:                             85.71
Df Residuals:                   15839   BIC:                             216.1
Df Model:                          16
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const               -0.0024      0.002     -1.247      0.213      -0.006       0.001
year                 0.0661      0.001     49.588      0.000       0.063       0.069
km_driven           -0.0173      0.002     -8.122      0.000      -0.021      -0.013
mileage             -0.0500      0.003    -14.731      0.000      -0.057      -0.043
engine               0.0306      0.005      6.393      0.000       0.021       0.040
max_power            0.0284      0.004      6.566      0.000       0.020       0.037
age                 -0.0661      0.001    -49.588      0.000      -0.069      -0.063
make                 0.0606      0.003     17.604      0.000       0.054       0.067
model                0.7896      0.005    171.092      0.000       0.781       0.799
Individual          -0.0176      0.002     -8.742      0.000      -0.022      -0.014
Trustmark Dealer    -0.0029      0.002     -1.499      0.134      -0.007       0.001
Diesel               0.0141      0.008      1.750      0.080      -0.002       0.030
Electric             0.0145      0.002      6.851      0.000       0.010       0.019
LPG                  0.0020      0.002      0.929      0.353      -0.002       0.006
Petrol              -0.0236      0.008     -2.846      0.004      -0.040      -0.007
Manual              -0.0132      0.003     -5.116      0.000      -0.018      -0.008
5                   -0.0287      0.007     -4.352      0.000      -0.042      -0.016
>5                  -0.0361      0.007     -5.221      0.000      -0.050      -0.023
==============================================================================
Omnibus:                     3635.549   Durbin-Watson:                   1.990
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           152535.136
Skew:                           0.288   Prob(JB):                         0.00
Kurtosis:                      18.184   Cond. No.                     2.01e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.78e-26. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [52]:
## VIF calculation

from statsmodels.stats.outliers_influence import variance_inflation_factor

# creating empty dataframe for VIF
vif = pd.DataFrame()

#creating copy of scaled training dataset
X_t = X_train_scaled_df


vif['Features'] =  X_t.columns
vif['VIF'] = [variance_inflation_factor(X_t.values,i) for i in range(X_t.shape[1])]

vif['VIF'] = np.round(vif['VIF'],2)
vif = vif.sort_values(by = 'VIF', ascending = False )
vif

/usr/local/lib/python3.10/dist-packages/statsmodels/stats/outliers_influence.py:198: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)

            Features    VIF
0               year    inf
5                age    inf
13            Petrol  18.47
10            Diesel  17.59
16                >5  12.91
15                 5  11.73
3             engine   6.17
7              model   5.74
4          max_power   5.05
6               make   3.19
2            mileage   3.11
14            Manual   1.80
12               LPG   1.25
1          km_driven   1.22
11          Electric   1.21
8         Individual   1.09
9   Trustmark Dealer   1.02

In [54]:
## Removing the variable with highest VIF
cols2 = vif['Features'][1:].values
cols2

array(['age', 'Petrol', 'Diesel', '>5', '5', 'engine', 'model',
       'max_power', 'make', 'mileage', 'Manual', 'LPG', 'km_driven',
       'Electric', 'Individual', 'Trustmark Dealer'], dtype=object)

In [58]:
X2 = pd.DataFrame(X_train_scaled, columns=X_train.columns)[cols2]
X2.head()

,age,Petrol,Diesel,>5,5,engine,model,max_power,make,mileage,Manual,LPG,km_driven,Electric,Individual,Trustmark Dealer
0,-1.080561,-0.974714,1.012694,-0.426052,0.446638,0.202493,1.373254,0.622383,-0.328974,0.228902,0.496726,-0.056805,-0.740637,-0.022468,1.248462,-0.098382
1,-1.080561,1.025942,-0.987465,-0.426052,0.446638,-0.535794,-0.195688,-0.361629,-0.435239,0.318461,-2.013182,-0.056805,-0.740637,-0.022468,-0.800986,-0.098382
2,0.170142,-0.974714,1.012694,-0.426052,0.446638,0.233176,-0.431817,0.119296,-0.242346,0.228902,0.496726,-0.056805,0.052608,-0.022468,-0.800986,-0.098382
3,0.482817,-0.974714,1.012694,-0.426052,0.446638,0.041413,-0.400333,-0.183443,-0.248121,0.734104,0.496726,-0.056805,0.241476,-0.022468,-0.800986,-0.098382
4,-0.455210,-0.974714,1.012694,-0.426052,0.446638,-0.437995,-0.353107,-0.534496,-0.435239,1.308197,0.496726,-0.056805,-0.022939,-0.022468,-0.800986,-0.098382

In [62]:
X2_sm = sm.add_constant(X2)
sm_model = sm.OLS(Y_train_array, X2_sm).fit()
print(sm_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.941
Model:                            OLS   Adj. R-squared:                  0.941
Method:                 Least Squares   F-statistic:                 1.578e+04
Date:                Tue, 15 Aug 2023   Prob (F-statistic):               0.00
Time:                        07:35:03   Log-Likelihood:                -25.857
No. Observations:               15856   AIC:                             85.71
Df Residuals:                   15839   BIC:                             216.1
Df Model:                          16
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const               -0.0024      0.002     -1.247      0.213      -0.006       0.001
age                 -0.1321      0.003    -49.588      0.000      -0.137      -0.127
Petrol              -0.0236      0.008     -2.846      0.004      -0.040      -0.007
Diesel               0.0141      0.008      1.750      0.080      -0.002       0.030
>5                  -0.0361      0.007     -5.221      0.000      -0.050      -0.023
5                   -0.0287      0.007     -4.352      0.000      -0.042      -0.016
engine               0.0306      0.005      6.393      0.000       0.021       0.040
model                0.7896      0.005    171.092      0.000       0.781       0.799
max_power            0.0284      0.004      6.566      0.000       0.020       0.037
make                 0.0606      0.003     17.604      0.000       0.054       0.067
mileage             -0.0500      0.003    -14.731      0.000      -0.057      -0.043
Manual              -0.0132      0.003     -5.116      0.000      -0.018      -0.008
LPG                  0.0020      0.002      0.929      0.353      -0.002       0.006
km_driven           -0.0173      0.002     -8.122      0.000      -0.021      -0.013
Electric             0.0145      0.002      6.851      0.000       0.010       0.019
Individual          -0.0176      0.002     -8.742      0.000      -0.022      -0.014
Trustmark Dealer    -0.0029      0.002     -1.499      0.134      -0.007       0.001
==============================================================================
Omnibus:                     3635.549   Durbin-Watson:                   1.990
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           152535.136
Skew:                           0.288   Prob(JB):                         0.00
Kurtosis:                      18.184   Cond. No.                         12.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [64]:
vif_thr = 5
r2_thr = 0.85
i = 1
feats_removed = ['year']
while True:
  vif = pd.DataFrame()
  X_t = pd.DataFrame(X_train_scaled, columns=X_train.columns)[cols2]
  vif['Features'] = cols2
  vif['VIF'] = [variance_inflation_factor(X_t.values, i) for i in range(X_t.shape[1])]
  vif['VIF'] = round(vif['VIF'], 2)
  vif = vif.sort_values(by = "VIF", ascending = False)

  cols2 = vif["Features"][1:].values
  X2 = pd.DataFrame(X_train_scaled, columns=X_train.columns)[cols2]

  X2_sm = sm.add_constant(X2)  #Statmodels default is without intercept, to add intercept we need to add constant
  sm_model = sm.OLS(list(Y_train_array), X2_sm).fit()
  if (vif.iloc[0]['VIF'] < vif_thr) or (sm_model.rsquared_adj < r2_thr):
    print('Reached threshold')
    print('Highest vif:',vif.iloc[0])
    print('Current adj.R2',sm_model.rsquared_adj)
    print('Features removed:', i)
    print('List of features removed:', feats_removed)
    break
  feats_removed.append(vif.iloc[0]['Features'])
  i += 1

Reached threshold
Highest vif: Features    max_power
VIF               2.7
Name: 0, dtype: object
Current adj.R2 0.7967548179952033
Features removed: 1
List of features removed: ['year']

In [65]:
print(vif)
print(sm_model.summary())

            Features   VIF
0          max_power  2.70
1               make  2.33
2            mileage  2.19
4             Manual  1.68
5             Diesel  1.51
6                  5  1.44
3                age  1.31
7          km_driven  1.21
8           Electric  1.15
9         Individual  1.08
10  Trustmark Dealer  1.02
11               LPG  1.01
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.797
Model:                            OLS   Adj. R-squared:                  0.797
Method:                 Least Squares   F-statistic:                     5651.
Date:                Tue, 15 Aug 2023   Prob (F-statistic):               0.00
Time:                        07:52:34   Log-Likelihood:                -9821.7
No. Observations:               15856   AIC:                         1.967e+04
Df Residuals:                   15844   BIC:                         1.976e+04
Df Model:                          11
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const               -0.0024      0.004     -0.672      0.501      -0.009       0.005
make                 0.4970      0.005    103.696      0.000       0.488       0.506
mileage             -0.2151      0.005    -43.763      0.000      -0.225      -0.205
Manual              -0.1762      0.005    -39.045      0.000      -0.185      -0.167
Diesel               0.2109      0.004     49.330      0.000       0.203       0.219
5                   -0.0516      0.004    -12.058      0.000      -0.060      -0.043
age                 -0.4178      0.004   -104.239      0.000      -0.426      -0.410
km_driven           -0.0334      0.004     -8.518      0.000      -0.041      -0.026
Electric             0.0652      0.004     17.121      0.000       0.058       0.073
Individual          -0.0503      0.004    -13.573      0.000      -0.058      -0.043
Trustmark Dealer    -0.0078      0.004     -2.170      0.030      -0.015      -0.001
LPG                  0.0019      0.004      0.535      0.593      -0.005       0.009
==============================================================================
Omnibus:                     1866.214   Durbin-Watson:                   1.990
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7311.231
Skew:                           0.547   Prob(JB):                         0.00
Kurtosis:                       6.142   Cond. No.                         2.66
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.